### ISSUE TITLE
tracking moved issues

### ISSUE THREAD

**Issue by samuelweiler** [w3c/horizontal-issue-tracker#19]
Figure out how tooling should deal with issues that a WG moves from one repo to another, as happened with https://github.com/w3cping/tracking-issues/issues/56  https://github.com/w3c/ttml2/issues/1202#event-3193192249

As practice, I propose that WGs should not be moving tracked issues.  They are welcome to **duplicate** an issue into a different repo/doc, but moving it off of a doc/repo is sufficiently equivalent to closing it that that should only happen with consent of the reviewer.  

With that assumed practice, what should the tooling do when an issue is moved?

**Comment by plehegar** [comment]
talking about this with @dontcallmedom last week or so, we'd like to propose something else:

Don't duplicate the issue into a different repo/doc since it has the drawback of splitting the discussion potentially. So let the Group moved the issue

To deal with this situation, the tool will act as follows:
1. when checking the status of horizontal issues, if an issue has been moved, add the label "moved?" *and* "pending" to the issue in the horizontal repo. The original link to the spec issue stays as-is, ie it stays associated as the original comment was made.

2. Once the horizontal group looks at the horizontal issue and  took action, remove the label "pending". There are 2 possible actions: 
 2.1 if the horizontal group wishes to agree that the issue should be moved and is no longer applicable to the original spec, the link in the horizontal issue should be updated to reflect the rediction and the label "moved?" should be removed.
 2.2 If the horizontal group disagrees with the move, keep the label "closed?". In this case, I suggest adding a comment in the horizontal issue indicating why there is disagreement on the move.

@samuelweiler @r12a @michael-n-cooper , how does this sound?

**Comment by samuelweiler** [comment]
Sounds pretty good.  This looks like it then defaults to keeping the issue tracked under the old spec/location, so if a review team doesn't triage the issue before the Director does a transition review, the issue still shows up on the old spec, which is the right thing.
