### ISSUE TITLE
Add spec title

### ISSUE THREAD

**Issue by plehegar** [w3c/horizontal-issue-tracker#3]
Having the shortname GH labels isn't enough. We need the specification titles as well.

**Comment by r12a** [comment]
Besides the fact that i'm wondering why (i18n hasn't felt a need for that so far), I fear that this will clutter up the interface too much. We could perhaps show the spec title if you click on some (small) item in the section header line (perhaps a right-aligned icon).

**Comment by samuelweiler** [comment]
I have mixed feelings about this.  My first instinct is "I want a short name of the spec or WG or something in the title of the issue".  I was doing that with a human-readable pre-tag, e.g. "WebAudio"; PING colleagues were including a partial URL to the spec / issue.  *shurg*  The current labels look like they might work for me, once I'm used to them.

**Comment by samuelweiler** [comment]
Having the titles in the issue text would be fine, and arguably helpful.  In fact, we could even copy in the first post in the issue thread, as context

**Comment by plehegar** [comment]
I added specification titles. Let me know if it clutters the board and need to be reverted.

fyi @wseltzer

**Comment by r12a** [comment]
I'm ok with the titles being spec titles, however it's a shame we appear to no longer have the short-names.  Since they are unique and short, it's often much quicker to search the page for the short-name, if you know it, rather than the long one.

The short-name doesn't need to be large, it could be in small letters floated to the end of the line with the title, for example.
