### ISSUE TITLE
Odd handling of CSS levels

### ISSUE THREAD

**Issue by svgeesus** [w3c/horizontal-issue-tracker#32]
Compare https://www.w3.org/PM/horizontal/review.html?shortname=css-color-4 with https://www.w3.org/PM/horizontal/review.html?shortname=css-color

The one [without an explicit level](https://www.w3.org/PM/horizontal/review.html?shortname=css-color) tells me the horizontal issues for CSS Color 4. The one [with an explicit level 4](https://www.w3.org/PM/horizontal/review.html?shortname=css-color-4) says there are no issues. I don't understand.

**Comment by plehegar** [comment]
The tool ignores levels by design. Thus, this is no s:css-color-4 label. And https://www.w3.org/PM/horizontal/reviews.html will only contain one entry for all CSS color levels.

The thinking was: for the rare case where css-color-4 would have a needs-resolution but not css-color-3, we would keep handling those cases manually, rather than relying on the automatic system to authorize the css color 3 publications.
