### ISSUE TITLE
No short label for some repos?

### ISSUE THREAD

**Issue by samuelweiler** [w3c/horizontal-issue-tracker#33]
Why does https://github.com/w3cping/tracking-issues/issues/242 not have a shortname label?

**Comment by samuelweiler** [comment]
Similarly, why does 
https://github.com/w3cping/tracking-issues/issues/233
(an issue pointing to the TAG design reviews repo) get a label whereas https://github.com/w3cping/tracking-issues/issues/239 does not?

**Comment by samuelweiler** [comment]
Here's another one: https://github.com/w3cping/tracking-issues/issues/245

**Comment by plehegar** [comment]
When a repository is associated with multiple shortnames, I usually have to go and add the label manually, because the tool [declines to pick one](https://github.com/w3c/horizontal-issue-tracker/blob/server/horizontal-task.js#L368).  So, I go and add those labels from time to time (which explains why I'm the one adding the label and not w3cbot).

For https://github.com/w3cping/tracking-issues/issues/233 and https://github.com/w3cping/tracking-issues/issues/239 , the tool isn't intelligent enough to know which spec is getting reviewed in the TAG design repo.

For https://github.com/w3cping/tracking-issues/issues/245 , https://github.com/w3c/personalization-semantics contains more than one document and the tool doesn't know how to differenciate.

The only exception is the csswg-drafts repository where, using the [CSS convention in the issue title](https://github.com/w3c/horizontal-issue-tracker/blob/server/horizontal-task.js#L375), the tool attempts to set the proper label.

**Comment by plehegar** [comment]
(closing for now)
