### ISSUE TITLE
Issue created with incorrect spec/shortname label

### ISSUE THREAD

**Issue by matatk** [w3c/horizontal-issue-tracker#38]
When the tool doesn't know the appropriate spec/shortname for an issue, I believe the intent is for it to not add one (ref: [the HR HOWTO](https://w3c.github.io/horizontal-issue-tracker/HOWTO) section "The tooling created a tracker issue in the HR repo but there was no s:xxx label. This means that the issues don't show up in the 'board'.").

I recently added `a11y-needs-resolution` to an issue, and the tracker created the HR tracking issue. However, it added a `s:html` label, even though this isn't an HTML issue (I don't think there really is a valid shortname, because it's a proposed charter for a new WG.

From the docs, I gather that an `s:*` label *must* be present in order for the issue to show up on the dashboard, so maybe this is intentional behaviour, but if so, perhaps a placeholder 'shortname' could be used, rather than `html`, as using `s:html` makes it show up in the wrong section in the dashboard?

The tracking issue is: w3c/a11y-review#177

P.S. This is a great tool, and the docs are clear and helpful; thanks!

**Comment by plehegar** [comment]
I removed the specification label since it's related to a charter as you concluded.

Ah, the strategy repo contains a lot related to several specifications. Not sure why the tool concluded it's only related to the HTML specification but that's either a bug or the tool reached the wrong conclusion.

The tool does require some manual interventions from time to time since we create new specifications or proposals all the time and things may move as well.

Those occurrences are occasional enough that I chose to keep the code as-is so far.
