### ISSUE TITLE
Issues without a shortname label are missing

### ISSUE THREAD

**Issue by plehegar** [w3c/horizontal-issue-tracker#5]

**Comment by r12a** [comment]
The i18n tracker GH issue list contains more things than just tracker items that belong on the review comment tracker (eg. it contains tracker data for our numerous lreq groups too). Stuff without an s:xxx label doesn't belong in the review comment tracker (but may be picked up by a different tracker).  So this is by design.

**Comment by plehegar** [comment]
the issue here is that other horizontal groups are flagging issues that aren't on specs, like issues on charter proposals. Thus, it would be nice to not forget those since they can be as important as spec issues. I guess more input is needed before we change things. @samuelweiler , got an opinion?

**Comment by samuelweiler** [comment]
PINGs use of its already-existing repo could have (and might have) included non-spec things.  If we wind up using the tracker, we'll probably need them to appear there.  (Right now, it's enough to just have the machinery in the background flipping labels.  I'm not using the tracker dashboard, really.)

**Comment by plehegar** [comment]
closing this for now. feel free to reopen if the issue is still relevant.
